- name: provision
  hosts: all
  become: yes
  gather_facts: true
  max_fail_percentage: 0
  vars:
    homedir: /home/vagrant
    git_name: eramuk
    git_email: eramuk@gmail.com
    packages:
      - git
      - zsh
  tasks:
    - name: set timezone to Asia/Tokyo
      timezone:
        name: Asia/Tokyo

    - name: install packages (rhel)
      yum:
        name: "{{ packages }}"
        state: latest
      when: ansible_os_family == "RedHat"

    - name: install packages (debian)
      apt:
        name: "{{ packages }}"
        state: latest
      when: ansible_os_family == "Debian"

    - name: git clone fzf
      git:
        repo: https://github.com/junegunn/fzf.git
        dest: "{{ homedir }}/.fzf"

    - name: install fzf
      shell:
        cmd: "yes | {{ homedir }}/.fzf/install"

    - name: git clone dotfiles
      git:
        repo: https://github.com/eramuk/dotfiles.git
        dest: "{{ homedir }}/src/dotfiles"

    - name: dotfiles symlink
      file:
        src: "{{ homedir }}/src/dotfiles/{{ item }}"
        dest: "{{ homedir }}/{{ item }}"
        state: link
        force: true
      loop:
        - .vimrc
        - .zshrc

    - name: git config
      git_config:
        scope: global
        name: "{{ item.name }}"
        value: "{{ item.value }}"
      loop:
        - name: user.name
          value: "{{ git_name }}"
        - name: user.email
          value: "{{ git_email }}"

    - name: enable zsh
      user:
        name: vagrant
        shell: /bin/zsh
